### ISSUE TITLE
Missing German stations

### ISSUE THREAD

**Issue by mackensen** [RailwayStations/Bahnhofsdaten#29]
How are German stations added to the dataset? There are two recent ones missing:

- Schopfheim-Schlattholz ([8311](https://www.bahnhof.de/en/id/8311)), opened 2017
- Stettfeld-Weiher ([8262](https://www.bahnhof.de/en/id/8262)), opened 2019

Other stations built in the last 6-7 years are in the dataset.

**Comment by pstorch** [comment]
Hi @mackensen single missing stations can be suggested via our website or android app. Long or right click on the Map.
