### ISSUE TITLE
Convert xlsx to csv

### ISSUE THREAD

**Issue by fossdd** [RailwayStations/Bahnhofsdaten#4]
xlsx files are binaries, and these stored in a git repository aren't really nice, or?

Yes, and i'm unable to open these files without MS Office or a compatible client like LibreOffice. 

GitHub can, cause CSV is a non-binary-file, show CSV files, only with an browser. (Also with a great view)

If you want to make something bold, maybe use markdown?

Also would great by replacing the `.ods`-file with converted text file.

**Comment by pstorch** [comment]
Hi @fossdd you are absolutely right about the data format. We (mis-)use this repository only as temporary storage. And the dataformat is what we get. We convert this data and import it in our database.
If you are interested in the raw data you can query the API, e.g. as json https://api.railway-stations.org/stations?country=de or text (csv) format: https://api.railway-stations.org/stations.txt?country=de

**Comment by pstorch** [comment]
But if you like you can convert them. PullRequests are welcome :wink:
